create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password_hash text not null,
  created_at bigint not null
);

create table if not exists public.saved_items (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  title text not null,
  item_type text not null default 'note',
  source text default '',
  url text default '',
  notes text default '',
  meta text default '',
  created_at bigint not null
);

create index if not exists saved_items_user_created_idx
  on public.saved_items (user_id, created_at desc);
